### ISSUE TITLE
[Feature Request] "link boxes" with same bg color of normal messages

### ISSUE THREAD

**Issue by Minibus93** [VChet/telegram-vanilla-dark-desktop#14]
Hello, 

first of all, thank you for realizing and maintening these theme, I feel that all of them greatly improves visibility while kicking a damn good style!

I don't know if you are up to "feature request" (to be honest, I don't even know if mine can be classified as one), but I'll try, feel free to close this/ignore ^^

Since I feel I'd make a big mess trying to explain what I mean without using a picture, I'll add a graphic explanation that will for sure be better!

![Immagine](https://user-images.githubusercontent.com/73554423/144406561-c658fd0b-6bb0-4dfa-afee-d6769dec0bc5.png)

Again, feel free to ignore this if this behavior is intended or you think it's better, great theme anyway and thanks again!

**Comment by VChet** [comment]
Hi,
Thanks for your feedback!

It won't be difficult to fix it. These "link boxes" are using `msgServiceBg` constant, which is also used in the date block. I guess it's ok if it will be changed too.
![](https://user-images.githubusercontent.com/17050347/144469640-bbd667cb-340b-493f-a145-81ee03ae0c23.png)

I will update themes soon
